namespace english_test.Words
{
    public static class Words
    {
        public static Dictionary<string, string> words = new()
        {
            { "hide", "ukryć się " },
            { "porridge", "owsianka " },
            { "land", "lądować " },
            { "ring", "dzwonić (ring/rang/rung) " },
            { "along", "wzdłuż " },
            { "sit", "siedzieć (sit/sat/sat) " },
            { "go", "iść (go/went/gone) " },
            { "have", "mieć (have/had/had) " },
            { "write", "pisać (write/wrote/written) " },
            { "rabbit", "królik " },
            { "cage", "klatka " },
            { "leave", "wychodzić, odchodzić, opuszczać (leave/left/left) " },
            { "live", "mieszkać " },
            { "Norway", "Norwegia " },
            { "get up", "wstawać " },
            { "get", "dostawać (get/got/got) " },
            { "listen to", "słuchać czegoś " },
            { "draw ", "pobrać " },
            { "tell", "powiedzieć (tell/told/told) " },
            { "say", "mówić (say/said/said) " },
            { "repairman", "konserwator " },
            { "give", "dawać (give/gave/given) " },
            { "advice", "rada (czasownik - poradzić) " },
            { "robber", "złodziej " },
            { "demand", "żądać " },
            { "cash register", "kasa " },
            { "see", "widzieć (see/saw/seen) " },
            { "sing", "śpiewać (sing/sang/sung) " },
            { "anyone else", "ktokolwiek inny " },
            { "to starve", "głodować " },
            { "break", "łamać, pękać, rozbić, tłuc (break/broke/broken) " },
            { "dessert", "deser " },
            { "train station", "stacja kolejowa " },
            { "pay", "płacić (pay/paid/paid) " },
            { "move", "przeprowadzać się " },
            { "borrow", "pożyczać " },
            { "movie", "film " },
            { "tonight", "wieczór " },
            { "feel", "czuć (feel/felt/felt) " },
            { "scare", "panikować " },
            { "homesickness", "tęsknota za domem " },
            { "hurry", "spieszyć się " },
            { "exciting", "pasjonujący " },
            { "exhilarating", "ekscytujący " },
            { "guilty", "winny " },
            { "responsibility", "odpowiedzialność " },
            { "find", "znaleźć (find/found/found) " },
            { "meet", "spotykać (meet/met/met) " },
            { "town", "miasto " },
            { "baboon", "pawian " },
            { "inside", "wewnątrz " },
            { "chase", "ścigać " },
            { "manage", "kierować, zarządzać " },
            { "imitate", "imitować " },
            { "rarely", "rzadko " },
            { "shoot", "kręcić np. film " },
            { "journalist", "dziennikarz " },
            { "odd", "dziwny " },
            { "occasion", "okazja " },
            { "cameraman", "kamerzysta " },
            { "interviewee", "osoba udzielająca wywiadu " },
            { "surroundings", "otoczenie " },
            { "tend", "mieć tendencje do… " },
            { "might", "móc " },
            { "slightly", "nieznacznie " },
            { "theatre", "teatr " },
            { "seat", "siedzenie " },
            { "behind", "za (kimś np.) " },
            { "loudly", "głośno " },
            { "angry", "zły " },
            { "turn round", "odwracać się " },
            { "look", "patrzeć " },
            { "angrily", "ze złością " },
            { "pay attention", "zwracać uwagę " },
            { "bear", "znieść " },
            { "rudely", "niegrzecznie " },
            { "carefully", "ostrożnie " },
            { "immediately", "natychmiast " },
            { "corner", "kąt/róg " },
            { "spoil", "zepsuć (spoil/spoilt/spoiled) " },
            { "greedily", "zachłannie " },
            { "beautifully", "pięknie " },
            { "draw", "rysować (draw/drew/drawn) " },
            { "build", "budować (build/built/built) " },
            { "village", "wieś " },
            { "match", "mecz " },
            { "receive", "otrzymywać np. list " },
            { "was", "był (be/was/were/been) " },
            { "hear", "słyszeć (hear/heard/heard) " },
            { "dress up", "ubieranie się " },
            { "Vamp it up (party time , make up...)", "Ubierz się (czas na imprezę, makijaż...) " },
            { "Put your glad rags on (put your stylish clothes)", "Załóż swoje radosne szmatki (włóż stylowe ubranie)  " },
            { "Wrap up warm", "Owiń się ciepło " },
            { "Wear ...a raincoat.", "Załóż ...płaszcz przeciwdeszczowy " },
            { "Put on...a fancy dress", "Załóż ...fantazyjny strój " },
            { "shabby", "znoszony " },
            { "designer", "projektant " },
            { "tailor-made", "wykonany na zamówienie/szyty na miarę " },
            { "handmade", "wykonany ręcznie " },
            { "ready made", "gotowy do noszenia " },
            { "uniform", "mundurek " },
            { "protective", "ochronny " },
            { "Sunday best", "najlepsza niedziela " },
            { "Smart/casual", "elegancki/swobodny " },
            { "Evening wear (bow tie, black tie, tuxedo)", "trój wieczorowy (muszka, czarny krawat, smoking)  " },
            { "Professional work attire (to go to the office)", "profesjonalny strój roboczy (do pracy w biurze) " },
            { "Footwear", "obuwie " },
            { "Headgear", "nakrycie głowy " },
            { "Underwear", "bielizna " },
            { "Sportswear", "odzież sportowa " },
            { "Swimwear", "strój kąpielowy " },
            { "Sleepwear", "bielizna nocna/pidżamy " },
            { "Clothes, clothing, garments, wear, dress, outfit, attire, apparel", "synonimy - ubrania " },
            { "Fashion, fashionable style, vogue, trendy, stylish, haute couture– stylowy modny ubiór", "synonimu " },
            { "Coat", "płaszcz " },
            { "winter coat", "płaszcz zimowy " },
            { "fur coat", "płaszcz futrzany " },
            { "overcoat", "palto " },
            { "raincoat", "płaszcz przeciwdeszczowy " },
            { "leather jacket", "kurtka skórzana " },
            { "bomber jacket", "kurtka bomberka " },
            { "tweed jacket", "kurtka tweedowa " },
            { "sports jacket", "kurtka sportowa " },
            { "sheepskin", "kożuch " },
            { "parka", "parka " },
            { "snowsuit", "kombinezon śnieżny " },
            { "slicker", "kominiarka " },
            { "casual dress", "sukienka codzienna " },
            { "formal dress", "sukienka wizytowa " },
            { "summer dress", "sukienka letnia " },
            { "cocktail dress", "sukienka koktajlowa " },
            { "evening dress", "sukienka wieczorowa " },
            { "evening gown", "sukienka wieczorowa " },
            { "button-through dress", "sukienka na guziki " },
            { "pinafore dress", "sukienka typu pinafore " },
            { "sweater", "sweter " },
            { "jersey", "dżersej " },
            { "cardigan", "cardigan " },
            { "pullover", "pulower " },
            { "jumper", "sweter " },
            { "turtle-neck", "golf " },
            { "pleated skirt", "plisowana spódnica " },
            { "trousers", "spodnie: pants, slacks, trousers, jeans, denims, shorts; leggings " },
            { "swimsuit", "strój kąpielowy " },
            { "swimming suit", "kostium kąpielowy " },
            { "bathing suit", "kąpielówki " },
            { "bikini/tankini", "bikini/tankini" },
            { "business suit", "garnitur biznesowy " },
            { "three-piece suit", "garnitur trzyczęściowy " },
            { "tuxedo", "smoking " },
            { "Black tie", "czarny krawat " },
            { "bow tie", "muszka " },
            { "combat trousers", "spodnie bojówki " },
            { "tracksuit", "dres " },
            { "trunks", "kąpielówki " },
            { "sweatshirt", "bluza " },
            { "hoodie", "bluza z kapturem " },
            { "Leisure time", "czas wolny " },
            { "Panties", "majtki " },
            { "Knickers", "figi " },
            { "Bra", "biustonosz " },
            { "Slip", "halka " },
            { "Half slip", "półhalka " },
            { "Leggings", "leginsy " },
            { "Stockings", "pończochy " },
            { "Tights", "rajstopy " },
            { "Knee-high socks", "podkolanówki " },
            { "Briefs", "majtki " },
            { "Boxers", "bokserki " },
            { "Underpants", "kalesony " },
            { "Long johns", "długie spodnie " },
            { "Undershirt", "podkoszulek " },
            { "Socks", "skarpety " },
            { "Pyjamas", "piżama " },
            { "Nightgown", "koszula nocna " },
            { "Bathing robe", "szlafrok kąpielowy " },
            { "abroad", "za granicą " },
            { "sunbathing", "opalanie " },
            { "a habit", "nawyk/zwyczaj " },
            { "belong", "należeć do " },
            { "depend", "zależny " },
            { "realize", "realizować " },
            { "recognize", "rozpoznawać " },
            { "seem", "wydawać się " },
            { "suppose", "przypuszczać coś " },
            { "sunscreen", "ochrona przeciwsłoneczna  " },
            { "cruise", "rejs " },
            { "arrive", "przyjechać/przybyć czymkolwiek  " },
            { "smell", "zapach " },
            { "burn", "płonąć " },
            { "overtime", "nadgodziny " },
            { "save up for", "oszczędzać/zbierać na coś " },
            { "cut down", "redukować/zmniejszyć np. cenę " },
            { "rise", "wschodzenie np. słońca " },
            { "cough", "kaszel " },
            { "flat", "mieszkanie " },
            { "traffic", "ruch drogowy " },
            { "traffic jam", "korek uliczny " },
            { "quietly", "cicho (przysłówek) " },
            { "cheap", "tanio  " },
            { "spare", "zapasowy " },
            { "memory card", "karta pamięci " },
            { "ahead", "naprzód " },
            { "journey", "podróż " },
            { "nearly", "prawie, niemalże " },
            { "midnight", "północ " },
            { "get in", "wsiadać " },
            { "daily grind", "codzienna harówka " },
            { "early", "wcześnie " },
            { "until", "do " },
            { "frequently", "często " },
            { "rush hour", "godziny szczytu " },
            { "canteen", "stołówka " },
            { "folding bike", "rower składany " },
            { "underground/tube", "metro " },
            { "crowded", "zatłoczony  " },
            { "(I'll be) __back  in a bit", "(I'll) return soon " },
            { "a full ___English_____ breakfast", "a cooked breakfast, usually with bacon, sausage, eggs, mushrooms, beans, tomatoes, toast and tea " },
            { "all ____over____ the world", "everywhere around the earth " },
            { "the rush ___hour___", "the period of time in the morning and evening when the traffic is very busy with people going to and from work " },
            { "to take a __long______ time", "to happen slowly " },
            { "to do something on __an empty________ stomach", "without any food before  " },
            { "kick", "kopać np. piłkę " },
            { "catch", "łapać " },
            { "carry", "nosić " },
            { "landlady", "właścicielka " },
            { "heating", "ogrzewanie " },
            { "essays", "wypracowania " },
            { "at Oxford Circus station", "na stacji Oxford Circus " },
            { "get the tube to work", "dojeżdżam do pracy metrem " },
            { "I have to commute to work", "muszę dojeżdżać do pracy " },
            { "I normally leave for work at 7.00", "zwykle wychodzę do pracy o 7.00 " },
            { "I usually get the train to…", "zazwyczaj jeżdżę pociągiem do… " },
            { "I usually hop on the bus.", "zazwyczaj wsiadam do autobusu " },
            { "I walk", "idę pieszo " },
            { "I’m knackered = I’m very, very tired.", "jestem bardzo, bardzo zmęczony " },
            { "I'm in the office from nine to five on an average day", "W przeciętny dzień jestem w biurze od 9 do 5 " },
            { "I'm on the bus for forty minutes", "jadę w autobusie 40 minut " },
            { "It’s a nightmare.", "to jest koszmar " },
            { "It’s very crowded", "jest bardzo tłoczno " },
            { "it's the middle of the rush hour", "jest środek godzin szczytu " },
            { "my commute isn't too long", "mój dojazd do pracy nie jest zbyt długi " },
            { "My office is based just off Bem Square", "moje biuro mieści się tuż przy placu Bema " },
            { "on their way home", "w drodze do domu " }
        };
    }
}
